name: Go
on: [push, pull_request]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Build Utility
      run: |
        make install

    - name: Run Tests
      run: |
        curl https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3 | bash
        sudo wget -qO- ${OC_BINARY_URL} | sudo tar -xvz -C /bin
        sudo pip install yq
        make test_e2e
      env:
        OC_BINARY_URL: https://mirror.openshift.com/pub/openshift-v4/clients/ocp/latest/openshift-client-linux-4.3.0.tar.gz
        YQ_BINARY: https://github.com/mikefarah/yq/releases/download/2.4.1/yq_linux_amd64
